version: '3.7'
services:
 hits:
  build: .
  image: hits:h4
  labels:
   - "traefik.frontend.rule=HostRegexp:{catchall:.*}"
  depends_on:
   - redis
  networks:
   - public
   - secret
 redis:
  image: redis:alpine
  volumes:
   - redis-data:/data
  networks:
   - secret
 loadbalancer:
  image: traefik
  command: --docker
  links:
   - hits
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  ports:
   - 8080:80
  networks:
   - public
volumes:
 redis-data:
  driver: local
  external: true
networks:
 secret:
  driver: bridge
 public:
  driver: bridge
